### ISSUE TITLE
UI: selection problem and ugly validation message

### ISSUE THREAD

**Issue by geziefer** [eclipse-ee4j/starter#254] opened 2023-05-08 12:47 UTC
If one selects "Jakarta EE 9.1" as version, the selection does not happen (1st image below), resulting in an ugly validation error when selecting something else (2nd image below)

![image](https://user-images.githubusercontent.com/9279978/236827972-6a1ac5dc-7357-4280-af8f-864527dd7379.png)

![image](https://user-images.githubusercontent.com/9279978/236828031-5f2e3652-c20e-4e5b-937d-121b4629fbbf.png)

**Comment by m-reza-rahman** [comment] 2023-05-08 14:15
It’s a good idea to test things out with the recent changes from Kito. I’ll do that myself too.

**Comment by m-reza-rahman** [comment] 2023-05-08 14:32
So far, cannot reproduce it in the latest code either. @geziefer, could you provide steps to reproduce including OS, browser and locale settings?

**Comment by geziefer** [comment] 2023-05-08 15:05
When I pull master branch as of now, do 
`mvn clean package wildfly:run`
open
`localhost:8080/jakarta-starter-ui`
and then select "Jakarta EE 9.1", I don't see the selection and the log states
` Validating form for Jakarta EE version: **91**, Jakarta EE profile: full, Java SE version: 17, Docker: false, runtime: none`
which is not covered by the switch case statement in Project.java.

It happens on Windows 11 with Chorme, Edge and Firefox (German locale) and Mac (English locale).
I thought it could be the locale in case "9.1" is interpreted as a number would be "9,1", so the "." might be deleted in conversion, but as said, same happens in English locale.

**Comment by geziefer** [comment] 2023-05-08 15:36
We might add that directly in the view's code since conversion is done from internal value, not from user input.
If I add
`locale="en-US"`
to the
`<f:convertNumber minFractionDigits="0" maxFractionDigits="1" />`
in index.xhtml for Jakarta EE version, the selection works.

**Comment by jeyvison** [comment] 2023-05-08 15:45
Just tested here and can't reproduce it on Mac(english Locale) using firefox or Safari. Weird

**Comment by geziefer** [comment] 2023-05-08 15:52
@jeyvison , @m-reza-rahman 
I think we should be safe to state explicitely to convert it in English number format in the view as it is only an internal value.

**Comment by m-reza-rahman** [comment] 2023-05-08 16:02
Do you mind issuing a PR? I think this is an issue of the server-side locale rather than client side.

**Comment by jeyvison** [comment] 2023-05-08 16:03
> Should I provide a PR for that?
Yes, please. But i'd like to understand a little bit more about the issue,also. Can you please share the JVM vendor and version you're using and the JVM locale(if thats different from OS)? From the images you shared it looks like you're using German somewhere?

**Comment by geziefer** [comment] 2023-05-08 16:09
Yes, it might be, as it happens for me also on my Mac with English language setting.
My JVM is "openjdk version "17.0.5" 2022-10-18" and if I print out my default locale it's "de_DE".

So, shouldn't be a problem for our production, but I'll file a PR with the little change, won't hurt there and might help others trying it out locally.

**Comment by jeyvison** [comment] 2023-05-08 16:22
Got it. Thanks for the infos :)

**Comment by jeyvison** [comment] 2023-05-08 16:25
@geziefer The PR is already merged, would mind test the latest master to confimr that #255 fixed it, please?

**Closed** 2023-05-08 16:50 UTC

**Comment by geziefer** [comment] 2023-05-08 16:53
Yes, works fine now.
